### ISSUE TITLE
Looking for instructions on how to relate the implementation to the CARE-SM data models

### ISSUE THREAD

**Issue by wna-se** [CARE-SM/CARE-SM-Implementation#7]
I’m trying to understand how to use the CSV template to populate the CARE-SM model with information from a typical sequencing experiment and was wondering if there is a showcase with examples of how these or similar mappings have been done somewhere? Or perhaps an example of how the different [Common Elements for Rare Disease Registration](https://eu-rd-platform.jrc.ec.europa.eu/sites/default/files/CDS/EU_RD_Platform_CDS_Final.pdf) can be extracted from the CSV implementation?

**Example:** A typical sequencing experiment submitted to the European Genome–Phenome Archive (EGA).

I have information about the entities outlined in the following diagram:
![EGA metadata model](https://github.com/CARE-SM/CARE-SM-Implementation/assets/1221165/0535feb6-30c4-43a4-ad1e-27531efb73ba)

How would I for example map information associated with a `Sample` to the [CARE-SM Biobank data model](https://github.com/CARE-SM/CARE-Semantic-Model/wiki/CARE-SM-Biobank)? Looking at [YARRRML/CARE_Fiab_yarrrml.yaml](https://github.com/CARE-SM/CARE-SM-Implementation/blob/main/YARRRML/CARE_Fiab_yarrrml.yaml) is seems like all of the model specific information is mapped to rdfs:label and I can‘t figure out where or how to add a link to the biobank.

**Comment by wna-se** [comment]
@pabloalarconm : @markwilkinson Said that you might be able to help with this.

**Comment by pabloalarconm** [comment]
Hi @wna-se 

CARE-SM is a patient-centric data model, rather than a sample-centric data model. The main assessment for Genetic data is the semantic relationship of a patient, in genetic testing process, where the output is the (normally pathogenic) genetic variant detected, defined by a URL annonation code. Other additional element can be added to this representation:
* Nature of the variant annonation (DNA, mRNA, etc)
* The Zygosity
* Specific genetic method, e.g. Microarray
* The nature of the anatomical structure where its extraction was sampled: e.g. Blood.

The documentation for populating the csv template is here:
https://github.com/CARE-SM/CARE-SM-Implementation/tree/main/CSV#genetic-assessment

Exampler use case for genetic information:
```csv
model,pid,protocol_id,frequency_type,frequency_value,value_datatype,comments,startdate,enddate,age,event_id,value,valueIRI,activity,target,agent,input,unit
Genotype,50012001,,,,xsd:string,,1998-06-30,1998-06-30,,788455685,601556,https://www.omim.org/entry/601556,,http://purl.obolibrary.org/obo/NCIT_C97927,http://purl.obolibrary.org/obo/GENO_0000136,,
```

Could you give me an example of how this sample information is represented? Is somehow broadly related to our `input` column in the CSV template.

Thank you,
Pablo
